<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Stage;

class StageSeeder extends Seeder
{
    public function run()
    {
        $stages = [
            [
                'titre' => 'Développeur Web Full Stack',
                'slug' => 'developpeur-web-full-stack',
                'description' => 'Nous recherchons un stagiaire passionné par le développement web pour rejoindre notre équipe. Vous travaillerez sur des projets Laravel et React.',
                'entreprise_id' => 1,
                'ville_id' => 1,
                'adresse_exacte' => 'Sonatel, Route de l\'Aéroport, Dakar',
                'duree' => '6 mois',
                'remuneration' => true,
                'montant_remuneration' => 150000,
                'date_debut' => '2026-09-01',
                'date_fin' => '2027-02-28',
                'type' => 'technique',
                'statut' => 'ouvert',
                'competences_requises' => 'PHP, Laravel, JavaScript, React, MySQL',
                'nb_postes' => 2,
                'date_limite_candidature' => '2026-08-15',
            ],
            [
                'titre' => 'Assistant Marketing Digital',
                'slug' => 'assistant-marketing-digital',
                'description' => 'Stage en marketing digital pour gérer les réseaux sociaux, créer du contenu et analyser les campagnes.',
                'entreprise_id' => 2,
                'ville_id' => 1,
                'adresse_exacte' => 'Orange, Dakar Plateau',
                'duree' => '4 mois',
                'remuneration' => true,
                'montant_remuneration' => 120000,
                'date_debut' => '2026-10-01',
                'date_fin' => '2027-01-31',
                'type' => 'professionnel',
                'statut' => 'ouvert',
                'competences_requises' => 'Marketing digital, SEO, Social Media, Créativité',
                'nb_postes' => 1,
                'date_limite_candidature' => '2026-09-15',
            ],
            [
                'titre' => 'Analyste Financier',
                'slug' => 'analyste-financier',
                'description' => 'Stage en analyse financière pour assister l\'équipe dans la gestion des portefeuilles et l\'analyse des risques.',
                'entreprise_id' => 3,
                'ville_id' => 1,
                'adresse_exacte' => 'Ecobank, Avenue Cheikh Anta Diop',
                'duree' => '5 mois',
                'remuneration' => true,
                'montant_remuneration' => 130000,
                'date_debut' => '2026-09-15',
                'date_fin' => '2027-02-15',
                'type' => 'professionnel',
                'statut' => 'ouvert',
                'competences_requises' => 'Finance, Excel, Analyse de données, Anglais',
                'nb_postes' => 2,
                'date_limite_candidature' => '2026-09-01',
            ],
            [
                'titre' => 'Ingénieur Réseaux et Télécoms',
                'slug' => 'ingenieur-reseaux-telecoms',
                'description' => 'Stage en ingénierie des réseaux pour travailler sur l\'infrastructure télécoms et la 5G.',
                'entreprise_id' => 1,
                'ville_id' => 2,
                'adresse_exacte' => 'Sonatel, Pikine',
                'duree' => '6 mois',
                'remuneration' => true,
                'montant_remuneration' => 160000,
                'date_debut' => '2026-10-01',
                'date_fin' => '2027-03-31',
                'type' => 'technique',
                'statut' => 'ouvert',
                'competences_requises' => 'Réseaux, IP, Cisco, Fibre optique',
                'nb_postes' => 1,
                'date_limite_candidature' => '2026-09-20',
            ],
            [
                'titre' => 'Chargé de Recrutement',
                'slug' => 'charge-recrutement',
                'description' => 'Stage en gestion des ressources humaines pour assister dans le processus de recrutement.',
                'entreprise_id' => 4,
                'ville_id' => 1,
                'adresse_exacte' => 'BRM, Avenue Cheikh Anta Diop',
                'duree' => '4 mois',
                'remuneration' => true,
                'montant_remuneration' => 100000,
                'date_debut' => '2026-11-01',
                'date_fin' => '2027-02-28',
                'type' => 'professionnel',
                'statut' => 'ouvert',
                'competences_requises' => 'RH, Communication, Gestion de projets',
                'nb_postes' => 1,
                'date_limite_candidature' => '2026-10-15',
            ],
            [
                'titre' => 'Développeur Mobile React Native',
                'slug' => 'developpeur-mobile-react-native',
                'description' => 'Stage pour développer des applications mobiles avec React Native pour le secteur bancaire.',
                'entreprise_id' => 3,
                'ville_id' => 1,
                'adresse_exacte' => 'Ecobank, Dakar',
                'duree' => '6 mois',
                'remuneration' => true,
                'montant_remuneration' => 145000,
                'date_debut' => '2026-12-01',
                'date_fin' => '2027-05-31',
                'type' => 'technique',
                'statut' => 'ouvert',
                'competences_requises' => 'React Native, JavaScript, API REST, Firebase',
                'nb_postes' => 2,
                'date_limite_candidature' => '2026-11-15',
            ],
            [
                'titre' => 'Responsable Qualité HACCP',
                'slug' => 'responsable-qualite-haccp',
                'description' => 'Stage en contrôle qualité dans l\'industrie agroalimentaire.',
                'entreprise_id' => 7,
                'ville_id' => 1,
                'adresse_exacte' => 'Biscuiterie Sénégalaise, Zone Industrielle',
                'duree' => '4 mois',
                'remuneration' => true,
                'montant_remuneration' => 110000,
                'date_debut' => '2026-09-01',
                'date_fin' => '2026-12-31',
                'type' => 'professionnel',
                'statut' => 'ouvert',
                'competences_requises' => 'HACCP, Qualité, Microbiologie, Normes ISO',
                'nb_postes' => 1,
                'date_limite_candidature' => '2026-08-20',
            ],
            [
                'titre' => 'Architecte Logiciel',
                'slug' => 'architecte-logiciel',
                'description' => 'Stage en architecture logicielle pour concevoir des systèmes scalables.',
                'entreprise_id' => 1,
                'ville_id' => 13,
                'adresse_exacte' => 'Sonatel, Thiès',
                'duree' => '6 mois',
                'remuneration' => true,
                'montant_remuneration' => 150000,
                'date_debut' => '2026-10-15',
                'date_fin' => '2027-04-15',
                'type' => 'technique',
                'statut' => 'ouvert',
                'competences_requises' => 'Java, Spring Boot, Microservices, Cloud',
                'nb_postes' => 1,
                'date_limite_candidature' => '2026-09-30',
            ],
            [
                'titre' => 'Community Manager',
                'slug' => 'community-manager',
                'description' => 'Stage pour gérer la présence digitale et créer du contenu engageant.',
                'entreprise_id' => 2,
                'ville_id' => 13,
                'adresse_exacte' => 'Orange, Thiès',
                'duree' => '4 mois',
                'remuneration' => true,
                'montant_remuneration' => 95000,
                'date_debut' => '2026-11-01',
                'date_fin' => '2027-02-28',
                'type' => 'professionnel',
                'statut' => 'ferme',
                'competences_requises' => 'Social Media, Canva, Rédaction, Créativité',
                'nb_postes' => 1,
                'date_limite_candidature' => '2026-10-20',
            ],
            [
                'titre' => 'Data Scientist',
                'slug' => 'data-scientist',
                'description' => 'Stage en science des données pour analyser les données clients et créer des modèles prédictifs.',
                'entreprise_id' => 2,
                'ville_id' => 1,
                'adresse_exacte' => 'Orange, Dakar',
                'duree' => '6 mois',
                'remuneration' => true,
                'montant_remuneration' => 155000,
                'date_debut' => '2026-12-01',
                'date_fin' => '2027-05-31',
                'type' => 'recherche',
                'statut' => 'ouvert',
                'competences_requises' => 'Python, Machine Learning, SQL, Statistiques',
                'nb_postes' => 2,
                'date_limite_candidature' => '2026-11-10',
            ],
            [
                'titre' => 'Chargé de Projet Énergie',
                'slug' => 'charge-projet-energie',
                'description' => 'Stage en gestion de projets énergétiques pour les infrastructures solaires.',
                'entreprise_id' => 6,
                'ville_id' => 1,
                'adresse_exacte' => 'Senelec, Dakar',
                'duree' => '5 mois',
                'remuneration' => true,
                'montant_remuneration' => 120000,
                'date_debut' => '2026-09-01',
                'date_fin' => '2027-01-31',
                'type' => 'professionnel',
                'statut' => 'ouvert',
                'competences_requises' => 'Gestion de projet, Énergie, Autocad, BIM',
                'nb_postes' => 1,
                'date_limite_candidature' => '2026-08-15',
            ],
            [
                'titre' => 'Consultant en Stratégie',
                'slug' => 'consultant-strategie',
                'description' => 'Stage en conseil stratégique pour accompagner les PME dans leur développement.',
                'entreprise_id' => 5,
                'ville_id' => 1,
                'adresse_exacte' => 'TotalEnergies, Dakar',
                'duree' => '4 mois',
                'remuneration' => true,
                'montant_remuneration' => 105000,
                'date_debut' => '2026-10-01',
                'date_fin' => '2027-01-31',
                'type' => 'professionnel',
                'statut' => 'ferme',
                'competences_requises' => 'Stratégie, Analyse de données, Communication',
                'nb_postes' => 1,
                'date_limite_candidature' => '2026-09-15',
            ],
            [
                'titre' => 'Administrateur Systèmes et Réseaux',
                'slug' => 'administrateur-systemes-reseaux',
                'description' => 'Stage en administration systèmes pour gérer l\'infrastructure IT.',
                'entreprise_id' => 4,
                'ville_id' => 1,
                'adresse_exacte' => 'BRM, Dakar',
                'duree' => '6 mois',
                'remuneration' => true,
                'montant_remuneration' => 130000,
                'date_debut' => '2026-11-15',
                'date_fin' => '2027-05-15',
                'type' => 'technique',
                'statut' => 'ouvert',
                'competences_requises' => 'Windows Server, Linux, Virtualisation, Sécurité',
                'nb_postes' => 1,
                'date_limite_candidature' => '2026-10-31',
            ],
            [
                'titre' => 'Assistant Achats et Logistique',
                'slug' => 'assistant-achats-logistique',
                'description' => 'Stage pour assister le service achats dans la gestion des fournisseurs.',
                'entreprise_id' => 9,
                'ville_id' => 1,
                'adresse_exacte' => 'ADM, Dakar',
                'duree' => '4 mois',
                'remuneration' => true,
                'montant_remuneration' => 95000,
                'date_debut' => '2026-10-01',
                'date_fin' => '2027-01-31',
                'type' => 'professionnel',
                'statut' => 'ouvert',
                'competences_requises' => 'Logistique, Achats, Excel, Négociation',
                'nb_postes' => 1,
                'date_limite_candidature' => '2026-09-20',
            ],
            [
                'titre' => 'Spécialiste en Cybersécurité',
                'slug' => 'specialiste-cybersecurite',
                'description' => 'Stage en cybersécurité pour auditer les systèmes et proposer des recommandations.',
                'entreprise_id' => 2,
                'ville_id' => 13,
                'adresse_exacte' => 'Orange, Thiès',
                'duree' => '6 mois',
                'remuneration' => true,
                'montant_remuneration' => 150000,
                'date_debut' => '2026-12-01',
                'date_fin' => '2027-05-31',
                'type' => 'technique',
                'statut' => 'ouvert',
                'competences_requises' => 'Sécurité informatique, Pentesting, Kali Linux',
                'nb_postes' => 2,
                'date_limite_candidature' => '2026-11-15',
            ],
            [
                'titre' => 'Responsable RSE',
                'slug' => 'responsable-rse',
                'description' => 'Stage en Responsabilité Sociétale des Entreprises pour piloter des projets durables.',
                'entreprise_id' => 5,
                'ville_id' => 1,
                'adresse_exacte' => 'TotalEnergies, Dakar',
                'duree' => '4 mois',
                'remuneration' => true,
                'montant_remuneration' => 100000,
                'date_debut' => '2026-09-01',
                'date_fin' => '2026-12-31',
                'type' => 'professionnel',
                'statut' => 'ferme',
                'competences_requises' => 'RSE, Développement durable, Communication',
                'nb_postes' => 1,
                'date_limite_candidature' => '2026-08-20',
            ],
            [
                'titre' => 'Développeur Intelligence Artificielle',
                'slug' => 'developpeur-intelligence-artificielle',
                'description' => 'Stage en IA pour développer des solutions innovantes en traitement du langage naturel.',
                'entreprise_id' => 1,
                'ville_id' => 1,
                'adresse_exacte' => 'Sonatel, Dakar',
                'duree' => '6 mois',
                'remuneration' => true,
                'montant_remuneration' => 160000,
                'date_debut' => '2026-10-15',
                'date_fin' => '2027-04-15',
                'type' => 'recherche',
                'statut' => 'ouvert',
                'competences_requises' => 'Python, TensorFlow, NLP, Transformers',
                'nb_postes' => 1,
                'date_limite_candidature' => '2026-09-30',
            ],
            [
                'titre' => 'Chargé de l\'Innovation et Développement',
                'slug' => 'charge-innovation-developpement',
                'description' => 'Stage pour explorer de nouvelles opportunités et innovations dans le secteur bancaire.',
                'entreprise_id' => 3,
                'ville_id' => 1,
                'adresse_exacte' => 'Ecobank, Dakar',
                'duree' => '5 mois',
                'remuneration' => true,
                'montant_remuneration' => 125000,
                'date_debut' => '2026-11-01',
                'date_fin' => '2027-03-31',
                'type' => 'professionnel',
                'statut' => 'ouvert',
                'competences_requises' => 'Innovation, Veille technologique, Stratégie',
                'nb_postes' => 1,
                'date_limite_candidature' => '2026-10-15',
            ],
            [
                'titre' => 'Architecte Cloud',
                'slug' => 'architecte-cloud',
                'description' => 'Stage en architecture Cloud pour migrer les infrastructures vers AWS et Azure.',
                'entreprise_id' => 2,
                'ville_id' => 1,
                'adresse_exacte' => 'Orange, Dakar',
                'duree' => '6 mois',
                'remuneration' => true,
                'montant_remuneration' => 155000,
                'date_debut' => '2026-12-01',
                'date_fin' => '2027-05-31',
                'type' => 'technique',
                'statut' => 'ouvert',
                'competences_requises' => 'AWS, Azure, Kubernetes, Docker',
                'nb_postes' => 2,
                'date_limite_candidature' => '2026-11-10',
            ],
            [
                'titre' => 'Responsable Communication Interne',
                'slug' => 'responsable-communication-interne',
                'description' => 'Stage en communication pour renforcer la cohésion interne.',
                'entreprise_id' => 10,
                'ville_id' => 1,
                'adresse_exacte' => 'La Sénégalaise d\'Assurances, Dakar',
                'duree' => '4 mois',
                'remuneration' => true,
                'montant_remuneration' => 95000,
                'date_debut' => '2026-09-15',
                'date_fin' => '2027-01-15',
                'type' => 'professionnel',
                'statut' => 'ouvert',
                'competences_requises' => 'Communication, Rédaction, Créativité',
                'nb_postes' => 1,
                'date_limite_candidature' => '2026-09-05',
            ],
        ];
        foreach ($stages as $stage) {
            Stage::create($stage);
        }
    }
}